"""queries table

Revision ID: 4c7ce67ef7d0
Revises: f79aca2eb712
Create Date: 2019-11-10 14:58:40.258405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7ce67ef7d0'
down_revision = 'f79aca2eb712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_user_id'), 'query', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_user_id'), table_name='query')
    op.drop_table('query')
    # ### end Alembic commands ###
