"""empty message

Revision ID: 77a965ec1375
Revises: f79aca2eb712
Create Date: 2019-11-17 13:33:35.996693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a965ec1375'
down_revision = 'f79aca2eb712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qqquery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=256), nullable=True),
    sa.Column('output', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qqquery_data'), 'qqquery', ['data'], unique=False)
    op.create_index(op.f('ix_qqquery_output'), 'qqquery', ['output'], unique=False)
    op.create_index(op.f('ix_qqquery_user_id'), 'qqquery', ['user_id'], unique=False)
    op.drop_index('ix_qquery_data', table_name='qquery')
    op.drop_index('ix_qquery_output', table_name='qquery')
    op.drop_index('ix_qquery_user_id', table_name='qquery')
    op.drop_table('qquery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qquery',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.VARCHAR(length=256), nullable=True),
    sa.Column('output', sa.VARCHAR(length=256), nullable=True),
    sa.Column('another', sa.VARCHAR(length=256), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qquery_user_id', 'qquery', ['user_id'], unique=False)
    op.create_index('ix_qquery_output', 'qquery', ['output'], unique=False)
    op.create_index('ix_qquery_data', 'qquery', ['data'], unique=False)
    op.drop_index(op.f('ix_qqquery_user_id'), table_name='qqquery')
    op.drop_index(op.f('ix_qqquery_output'), table_name='qqquery')
    op.drop_index(op.f('ix_qqquery_data'), table_name='qqquery')
    op.drop_table('qqquery')
    # ### end Alembic commands ###
